# Generated by Django 4.2 on 2023-05-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0006_profissao_cliente_id_profissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name_plural': 'Profissões'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_profissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CadastroCliente.profissao'),
        ),
    ]
