# Generated by Django 4.2 on 2023-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0007_alter_profissao_options_alter_cliente_id_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(choices=[('SOL', 'Solteiro'), ('CAS', 'Casado'), ('DIV', 'Divorciado'), ('VIU', 'Viúvo')], max_length=3, null=True),
        ),
    ]
