# Generated by Django 4.2 on 2023-05-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0008_cliente_estado_civil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_profissao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroCliente.profissao', verbose_name='Profissão'),
        ),
    ]
