# Generated by Django 4.2 on 2023-05-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0010_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='interesse',
            field=models.ManyToManyField(to='CadastroCliente.interesse'),
        ),
    ]
