# Generated by Django 4.2 on 2023-05-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0011_cliente_interesse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='interesse',
            new_name='interesses',
        ),
    ]
